### ISSUE TITLE
Crashing application on click of Camera button

### ISSUE THREAD

**Issue by mayurnemade7** [CBerthias/Document_scanner#1]
Process: com.example.openscan, PID: 29876
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.example.monscanner.CameraActivity.openCamera(CameraActivity.java:362)
        at com.example.monscanner.CameraActivity.access$600(CameraActivity.java:57)
        at com.example.monscanner.CameraActivity$7.onSurfaceTextureAvailable(CameraActivity.java:319)
        at android.view.TextureView.getTextureLayer(TextureView.java:406)
        at android.view.TextureView.draw(TextureView.java:349)

**Comment by ambessh** [comment]
@mayurnemade7 did you solve it. help me please .

**Comment by ambessh** [comment]
using default camera Mediastore.Action_Image_Capture solved the issue .
